---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
## Oppgave 2
## Setup - Laster ned nødvendige pakker

```{r message=TRUE, warning=FALSE}
library(tidyverse)
library(ggplot2)
```


```{r}
# Nedre troposfære
uahncdc_lt_6_0 <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")

# Filterer bort data vi ikke trenger, og grupperer med NoPol som er den variabelen vi skal fokusere på
nedre_tfaere <- uahncdc_lt_6_0 %>%
  filter(Year <= 2022) %>%
  select(Year, NoPol) %>%
  rename(NoPol_nedre_tfaere = NoPol, Years = Year)

nedre_tfaere$NoPol_nedre_tfaere <- as.numeric(nedre_tfaere$NoPol_nedre_tfaere)
nedre_tfaere$Years <- as.numeric(nedre_tfaere$Years)

# Midt troposfære
uahncdc_mt_6_0 <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")

midt_tfaere <- uahncdc_mt_6_0 %>%
  filter(Year <= 2022) %>%
  select(Year, NoPol) %>%
  rename(NoPol_midt_tfaere = NoPol)

midt_tfaere$NoPol_midt_tfaere <- as.numeric(midt_tfaere$NoPol_midt_tfaere)
midt_tfaere$Year <- as.numeric(midt_tfaere$Year)

# Tropopause
uahncdc_tp_6_0 <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")

tropopause <- uahncdc_tp_6_0 %>%
  filter(Year <= 2022) %>%
  select(Year, NoPol) %>%
  rename(NoPol_tropopause = NoPol)

tropopause$NoPol_tropopause <- as.numeric(tropopause$NoPol_tropopause)
tropopause$Year <- as.numeric(tropopause$Year)
# Nedre stratosfære
uahncdc_ls_6_0 <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")

nedre_ssfaere <- uahncdc_ls_6_0 %>%
  filter(Year <= 2022) %>%
  select(Year, NoPol) %>%
  rename(NoPol_nedre_ssfaere = NoPol)
  #group_by(NoPol) 

nedre_ssfaere$NoPol_nedre_ssfaere <- as.numeric(nedre_ssfaere$NoPol_nedre_ssfaere)
nedre_ssfaere$Year <- as.numeric(nedre_ssfaere$Year)

# Binder datasettene sammen
total <- cbind(nedre_tfaere, midt_tfaere, tropopause, nedre_ssfaere) %>%
# funket ikke å bruke unique eller distinct for å fjerne kolonnene som var duplisert. Bruker select
  select(Years, NoPol_nedre_ssfaere, NoPol_tropopause, NoPol_midt_tfaere, NoPol_nedre_tfaere)

# Regner gjennomsnittet for alle datasettene
snitt <- total %>%
  rowwise() %>%
  mutate(Mean=mean(c(nedre_tfaere, midt_tfaere, tropopause, nedre_ssfaere)))

# Omgjør gjennomsnittet til numerisk 
snitt %>% mutate_at(vars(NoPol_nedre_ssfaere, NoPol_tropopause, NoPol_midt_tfaere, NoPol_nedre_tfaere), ~as.numeric(.))


total %>%
  select(Years, NoPol_nedre_ssfaere, NoPol_tropopause, NoPol_midt_tfaere, NoPol_nedre_tfaere) %>%
  pivot_longer(-Years, names_to = "Verdi", values_to = "Temperature") %>%
  ggplot(aes(x=Years, y=Temperature, col=Verdi)) + 
  geom_line() +
  scale_y_continuous(limits = c(-10, 10),
                     breaks = scales::breaks_width(1)) +
  scale_x_continuous(limits = c(1979, 2022),
                     # endrer width til 2 så årstallene ikke blir så sammenklemt sammen :)
                     breaks = scales::breaks_width(2)) +
  scale_color_manual(name="Nivå i atmosfæren", 
                     labels=c("Nedre stratosfære","Tropopause","Midt troposfæren","Nedre troposfæren"), 
                     values = c("pink", "purple", "yellow", "red")) +
  #ggtitle("Atmosfæriske temperaturer") +
  labs(title="Atmosfæriske temperaturer",
       subtitle = "Perioden fra 1979-2021",
       x ="År",
       y = "Gjennomsnittlig temperaturavvik (celsius)") +
  theme_bw()

```{r}
```
